# base image Ubuntu 22.04
FROM ubuntu:jammy

ENV DEBIAN_FRONTEND=noninteractive

ARG CODE_DIR=/usr/local/src

#basic environment
RUN apt update && apt install -y \
    apt-utils \
    software-properties-common \
    wget \
    unzip \
    curl \
    ca-certificates \
    build-essential \
    git \
    cmake \
    cmake-curses-gui \
    libace-dev \
    libassimp-dev \
    libglm-dev \
    libeigen3-dev

# Suggested dependencies for OpenEB 4.6.2
RUN apt update && apt install -y \
    libopencv-dev \
    libgtest-dev \
    libboost-all-dev \
    libusb-1.0-0-dev \
    libeigen3-dev \
    libprotobuf-dev \
    protobuf-compiler
RUN apt update && apt install -y \
    libglew-dev \
    libglfw3-dev \
    libcanberra-gtk-module \
    ffmpeg && \
    rm -rf /var/lib/apt/lists/*

# Python environment for OpenEB
RUN apt update && apt -y install python3-pip python3-distutils
RUN apt update && apt -y install python3.10-dev  # where X is 8, 9 or 10 depending on your Python version (3.8, 3.9 or 3.10)
RUN python3 -m pip install pip --upgrade
RUN python3 -m pip install "opencv-python==4.5.5.64" "sk-video==1.1.10" "fire==0.4.0" "numpy==1.23.4" pandas scipy h5py
RUN python3 -m pip install jupyter jupyterlab matplotlib "ipywidgets==7.6.5" pytest command_runner

# Install pybind for OpenEB
RUN cd $CODE_DIR && \
    wget https://github.com/pybind/pybind11/archive/v2.6.0.zip && \
    unzip v2.6.0.zip && \
    cd pybind11-2.6.0 && \
    mkdir build && cd build && \
    cmake .. -DPYBIND11_TEST=OFF && \
    cmake --build . && \
    cmake --build . --target install

# Suggested dependencies for YARP
RUN apt update && apt install -y \
    qtbase5-dev qtdeclarative5-dev qtmultimedia5-dev \
    qml-module-qtquick2 qml-module-qtquick-window2 \
    qml-module-qtmultimedia qml-module-qtquick-dialogs \
    qml-module-qtquick-controls qml-module-qt-labs-folderlistmodel \
    qml-module-qt-labs-settings \
    libqcustomplot-dev \
    libgraphviz-dev \
    libjpeg-dev \
    libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
    gstreamer1.0-plugins-base \
    gstreamer1.0-plugins-good \
    gstreamer1.0-plugins-bad \
    gstreamer1.0-libav

# Add OpenEB 4.6.2 and build
ARG OPENEB_VERSION=4.6.2
RUN cd $CODE_DIR && \
    git clone --depth 1 --branch $OPENEB_VERSION https://github.com/prophesee-ai/openeb.git && \
    cd openeb && \
    mkdir build && cd build && \
    cmake .. -DBUILD_TESTING=OFF && \
    cmake --build . --config Release -- -j `nproc` && \
    cmake --build . --target install

# YCM
ARG YCM_VERSION=v0.15.2
RUN cd $CODE_DIR && \
    git clone --depth 1 --branch $YCM_VERSION https://github.com/robotology/ycm.git && \
    cd ycm && \
    mkdir build && cd build && \
    cmake .. && \
    make -j `nproc` install

# YARP
ARG YARP_VERSION=v3.8.0
RUN cd $CODE_DIR && \
    git clone --depth 1 --branch $YARP_VERSION https://github.com/robotology/yarp.git &&\
    cd yarp &&\
    mkdir build && cd build &&\
    cmake .. &&\
    make -j `nproc` install

EXPOSE 10000/tcp 10000/udp
RUN yarp check


# event-driven
ARG ED_VERSION=main
RUN cd $CODE_DIR &&\
    git clone --depth 1 --branch $ED_VERSION https://github.com/robotology/event-driven.git &&\
    cd event-driven &&\
    mkdir build && cd build &&\
    cmake .. &&\
    make -j `nproc` install

# Register all libraries in the cache
RUN ldconfig

# Remove downloaded source trees (optional)
RUN rm -rf \
    ${CODE_DIR}/pybind11-2.6.0 \
    ${CODE_DIR}/ycm \
    ${CODE_DIR}/openeb \
    ${CODE_DIR}/yarp

# Add User ID and Group ID
ARG UNAME=event-driven
ARG UID=1000
ARG GID=1000
RUN groupadd -g $GID -o $UNAME
RUN useradd -m -u $UID -g $GID -o -s /bin/bash $UNAME
RUN usermod -aG dialout ${UNAME}

# Add User into sudoers, can run sudo command without password
RUN apt update && apt install -y sudo && rm -rf /var/lib/apt/lists/*
RUN usermod -aG sudo ${UNAME}
RUN echo "${UNAME} ALL=(ALL) NOPASSWD:ALL" | tee /etc/sudoers.d/${UNAME}

# Change owner of some folders for the development
RUN chown -R $UNAME:$UNAME $CODE_DIR

# Change user and working directory
USER $UNAME
WORKDIR /home/${UNAME}