%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Given:
% - a *.txt input file (same format as the output of 'vbottletotxt_AE.m')
% - a codec type, and
% - the number of bits used to represent the timestamp
% Convert a *.txt file containing events data in the following format: 
% CH TS POL X Y BOTTLE_START YARP_TS
% e.g. 1 199671413 0 25 30 0 1558427718.1332604885
% to a *.log file of the following format:
% BOTTLE_ID YARP_TS AE (TS1 AE1 .... TSn AEn)
% e.g. 6749 1558705796.241420 AE (120032381 4870571 120032383 4870420)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% Initialization
CODEC_TYPE = 2;
TIMESTAMP_BITS = 30;
CLOCK_PERIOD = 0.000000080; % 80 nano-seconds
% The following input file has been generated by 'ECdatasetTotxt_AE.txt'
infilename = '/home/adinale/src/event-driven/matlab/conversion/eventsLog.txt';

if(~exist('infilename', 'var'))
    disp('Please specify the path to the dataset in parameter "infilename"');
    return;
end

if(~exist('CODEC_TYPE', 'var'))
    disp('Please specify CODEC_TYPE:');
    disp('0 - DVS_128x128');
    disp('1 - ATIS_20BIT');
    disp('2 - ATIS_24BIT');
    return;
end

if(~exist('TIMESTAMP_BITS', 'var'))
   disp('Please set TIMESTAMP_BITS (24 -> 31)');
   return;
end

switch CODEC_TYPE
    case 0
        CH = 1; TS = 2; POL = 3; X = 5; Y = 4; BOTTLE_START = 6; YARP_TS = 7;

        POLSH = 0;
        CHSH  = 15;
        XSH   = 1;
        YSH   = 8;
    case 1
        CH = 1; TS = 2; POL = 3; X = 4; Y = 5; BOTTLE_START = 6; YARP_TS = 7;

        POLSH = 0;
        CHSH  = 20;
        XSH   = 1;
        YSH   = 10; 
    case 2
        CH = 1; TS = 2; POL = 3; X = 4; Y = 5; BOTTLE_START = 6; YARP_TS = 7;

        POLSH = 0;
        CHSH  = 22;
        XSH   = 1;
        YSH   = 12;
end

%% Read input file (*.txt)
data = dlmread(infilename);

% Retrieve FPGA timestamps
w1 = bitor(bitshift(32, TIMESTAMP_BITS, 'int32'), int32(data(:, TS)));

% Retrieve AEs (channel, x, y and polarity)
w2 = int32(zeros(size(data, 1), 1));
w2 = bitor(w2, int32(bitshift(data(:, CH), CHSH, 'int32')), 'int32');
w2 = bitor(w2, int32(bitshift(data(:, X), XSH, 'int32')), 'int32');
w2 = bitor(w2, int32(bitshift(data(:, Y),  YSH, 'int32')), 'int32');
w2 = bitor(w2, int32(bitshift(data(:, POL), POLSH, 'int32')), 'int32');

% Retrieve the number of vBottles
indicies = find(data(:, BOTTLE_START));
numBottles = length(indicies);
% Add index for last row number of data
indicies = [indicies; length(data)]; 

%% Generate AE bottle output (*.log)
datafilename = 'data.log';

if isfile(datafilename)
    delete(datafilename);
end

datafile = fopen(datafilename, 'w+');

disp('Conversion starting ...');
for i = 1:numBottles

    % Write the vBottle of events
    fprintf(datafile, '%i %10.10f AE (', i, data(indicies(i), YARP_TS));
    
    if i == numBottles    
        for j = indicies(i):indicies(i+1)
            fprintf(datafile, '%i %i ', w1(j), w2(j));
        end
    else
        for j = indicies(i):(indicies(i+1)-1)
            fprintf(datafile, '%i %i ', w1(j), w2(j));
        end
    end
    fseek(datafile, -1, 'cof'); % cof = current position in file
    fprintf(datafile, ')\n');
    
    fprintf('Processed bottles: %i/%i \n', i, numBottles);        
end

% TODO: this script is missing the timestamp wrapping (for more details
% check 'vbottletotxt_AE.m')